# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2badbbef1ab1069e36979eefcc08941e1100edc6fbc23828d288d136640561d771f5d528bc8c8f484971bbae8202e2331f8312065fb88854d50e0d9da796186

test:
  secret_key_base: df70031a584845833520eb18bcf7c964e7bdc4122468b856ac5add48dc3479776b7fd6bffa2321c09b66fd413c69f9e833961be2ee948fb484d43dff2ee1c3f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
